# Generated by Django 3.0.8 on 2020-07-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comments',
        ),
        migrations.AddField(
            model_name='orderdish',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
