# Generated by Django 3.0.8 on 2020-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200717_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='distPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
