# Generated by Django 3.0.8 on 2020-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200721_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='distPrice',
            field=models.FloatField(),
        ),
    ]
