# Generated by Django 3.0.8 on 2020-07-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200721_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=22324, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=234234234242),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
